### ISSUE TITLE
Easier access to tooltip hints in UI

### ISSUE THREAD

**Issue by steadyk** [steadforce/k8s-escape-room#63]
We currently use tooltips in the UI which provide hints to the user for specific riddles.
These tooltips will be presented on moving the move over the red circles.
But the UI window need to be in focus.
This might be confusing if e.g. on working with multiple windows for the UI and e.g. `k9s`.

Maybe we can improve the accessibility to the hints for the user in some way?
Or we could mention that the UI window needs to be in focus in the readme.

We already have a short hint about the hints in the readme for codespaces and local. Is this present enough?

**Comment by peters-david** [comment]
After researching I think this might be more of a browser related problem. According to [this mozilla bug ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1861427) tooltips on non-focused windows works for many browsers, just not for firefox.
I can confirm, for me tooltip hints with another window in focus works in chromium, but not in firefox.

@steadyk maybe we should suggest using a specific browser when solving the escape room?

**Comment by steadyk** [comment]
Thanks for the research @peters-david!
I can confirm that the tooltips works also in an unfocused window in Chromium.
So maybe we could do the following (base on your suggestions):
* make the tooltip hint more visible for the user (e.g. on main page? Or in the sub-pages?)
* note that the tooltips can only be seen in Firefox if the browser window is active
* recommend using e.g. Chromium

Would ths make sense?

**Comment by peters-david** [comment]
Yes, so adding note that in firefox the window needs to be active and the browser recommendation.
What specifically do you mean by making the tooltip hints more visible?
Increasing the size of the red circles? Increasing the size of the tooltip hints? Changing the color of the tooltip hints?

**Comment by steadyk** [comment]
@peters-david
Sorry for the confusion! 
I meant the location in general. Currently the hints to the tooltips are in the specific sub readmes for codespaces and local which cloud maybe be overlooked.
Or are they present enough for us?

**Comment by peters-david** [comment]
No, you are right, I moved them to the end of the introduction of `README.md`.
